
common_words = {"edit", "edited", "comment", "comments", "anything", "anyone", "everyone",
                "everything", "lot", "lol", "get", "lot", "lots", "reddit",
                "uh", "oh", "wow", "yeah", "yep", "use", "day", "today",
                "bit", "ah", "thanks", "while", "subreddit", "see", "picture",
                "post", "idea", "kind", "let", "nothing", "stuff", "thing",
                "things", "yes", "no", "place", "places", "that", "thats",
                "way", "someone", "somebody", "kinda", "people", "person",
                "come", "wait", "awesome", "back", "fun", "guy", "boy", "girl", "he",
                "she", "tell", "thank", "time", "hell", "heck", "fact", "gt",
                "remember", "something", "looks", "look", "sorry", "shit", "fuck",
                "end", "fan", "please", "question", "guys", "days", "example",
                "news", "nope", "sort", "haha", "fine", "nobody", "try", "etc",
                "go", "let", "lets", "make", "makes", "nah", "super", "think",
                "thought", "op", "okay", "week", "month", "year", "years",
                "weeks", "months", "super", "great", "show", "am", "man", "woman",
                "ass", "cool", "video", "image", "read", "reading", "list",
                "needs", "omg", "sub", "subs", "room", "rooms", "tl", "alright",
                "aw", "beside", "besides", "change", "enjoy", "getting", "game",
                "games", "name", "names", "mind", "pictures", "server", "your",
                "yours", "posters", "point", "content", "opinion", "problem",
                "subreddits", "reason", "ok", "world", "part", "parts", "p",
                "mod", "mods", "rules", "/sp ", "e.g.", "i.e.", "situation",
                "work", "chance", "hour", "hours", "morning", "afternoon",
                "evening", "cause", "case", "number", "numbers", "ability",
                "abilities", "source", "upvotes", "downvotes", "life", "lives",
                "spoilerR ", "effect", "effects", "guess", "guesses", "twice",
                "amount", "computer", "computers", "money", "default", 
                "difference", "sense", "access", "a bit", "a girl", "a boy",
                "a lot", "email", "face", "none", "word", "words", "great idea",
                "job", "jobs", "internet", "matter", "times", "title", "dude",
                "bunch", "eh", "couple", "course", "touch", "finger",
                "hahaha", "information", "talk", "talks", "value", "ie",
                "need"}
